### ISSUE TITLE
mmc bug

### ISSUE THREAD

**Issue by RoyaleOne** [Rectify11/Installer#253]
### Description

some ui elements dont show highlights and just show a rounded grey box, is this normal
![image](https://github.com/Rectify11/Installer/assets/68414738/abba46cc-fdd9-4bff-80ab-922d8ad599ea)

![image](https://github.com/Rectify11/Installer/assets/68414738/2075431a-322e-4677-b6a9-0873c268a80f)

and in device manager (and some other ui elements overall) you cant see highlights underneath from what was selected

![image](https://github.com/Rectify11/Installer/assets/68414738/695b609d-53ef-4967-8846-d82ce883a2e1)
(the selected thing is vega 10 graphics)

other than this issue this modification is very good and good job to the people that made it!

### Steps To Reproduce

the steps to reproduce the issue are above

### Rectify11 Version

version 3.0 rc3

### Windows Version

Windows 11 Pro Build 22621.2215

### Logs

there's no log

**Comment by WinExperiments** [comment]
It's fixed as of RC2.

**Comment by RoyaleOne** [comment]
> It's fixed as of RC2.

well it isnt because im using that version

**Comment by WinExperiments** [comment]
Oh excuse me I meant a later actions build. Sorry for the inconvenience.

**Comment by RoyaleOne** [comment]
> Oh excuse me I meant a later actions build. Sorry for the inconvenience.

is there a way i could test that? i would love to do more bug testing

**Comment by WinExperiments** [comment]
Uninstall your current Rectify11 installation, then go to the "Actions" tab on this page, choose the latest you see, click "Rectify11Installer" to download it, then install as usual.

**Comment by WildByDesign** [comment]
@WinExperiments @MishaProductions With a due respect, I don't believe that this issue is fixed. I always use the latest Actions builds personally. Please allow me to explain this issue in more detail since I have been specifically digging into this issue for approx. 2 months now. I believe that this issue should be reopened.

### Cause:

**GDI Scaling.**
See: https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/

For whatever reason. the msstyles used by Rectify11 trigger this bug in any programs that use `GDIScaling`. Possibly due to how the Rectify11 msstyles use selective DPI per resource. `GDIScaling` does not use typical DPI awareness.


### Which programs are affected:

MMC is the most obvious because this issue affects the general usage of Device Manager, Task Scheduler, Event Viewer, Computer Management, Services, etc. as they become almost unusable.

Any programs that enable `GDIScaling` exhibit these same visual issues. Another example is Total Registry (https://github.com/zodiacon/TotalRegistry). Programs like that are easy to fix by enabling AppCompatFlags to enable `HIGHDPIAWARE` and therefore overriding the `GDIScaling`.

MMC cannot be fixed that way though because system files do not recognize AppCompatFlags.

### Who is affected by this bug:

From my testing, users who have their _Display - Scale_ set to 125%, 150% or higher will see these issues. So if you want to reproduce this issue, try setting your scaling to 125%, 150% or higher and do not use Custom scaling.

Users with their scaling set to 100% will **not** see these issues.

Users that enable _Custom scaling_ also will **not** see these issues. I assume in this cause because Windows forces different system DPI awareness per app specifically for apps which have DPI awareness set to `unaware`. With `GDIScaling` enabled, DPI awareness gets set to `unaware`. So this is why users who enable _Custom scaling_ do not see this issue. However, Microsoft states that _Custom scaling_ is not recommended due to potential issues.

### How to fix all of the MMC issues:

[MMC-Fix.zip](https://github.com/Rectify11/Installer/files/12575726/MMC-Fix.zip)

The mmc.exe binary has a built-in manifest which disables `dpiAware` and enables `GDIScaling`. Therefore, to fix this we need to override the `GDIScaling`. This cannot be done via regular AppCompatFlags since this is a system file.

First, we need to enable `PreferExternalManifest`. This allows mmc.exe to utilize the external manifest.

You can either merge the attached `PreferExternalManifest.reg` file, or within the Rectify11 installer scripts you can run the following elevated command: `REG ADD "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\SideBySide" /v PreferExternalManifest /t REG_DWORD /d 1 /f`

After that, you need to copy the `mmc.exe.manifest` to `C:\Windows\System32` so that it is in the same directory as `mmc.exe`.

You do not need to reboot or logout for this fix to take affect. It works immediately.

**Comment by RoyaleOne** [comment]
Yeah, it isnt fixed and its on a laptop with 125% dpi scaling

**Comment by WildByDesign** [comment]
Can you try my fix and confirm whether it is successful or not?

It fixed all MMC issues for me. But more confirmation from other users would be good.

**Comment by RoyaleOne** [comment]
No

> Can you try my fix and confirm whether it is successful or not?
> 
> It fixed all MMC issues for me. But more confirmation from other users would be good.

I will try it when i can and I'll tell you

**Comment by EDM115** [comment]
> Can you try my fix and confirm whether it is successful or not?
> 
> It fixed all MMC issues for me. But more confirmation from other users would be good.

It indeed does work <3

**Comment by WildByDesign** [comment]
@rounk-ctrl  You recently submitted the mmc fix (https://github.com/Rectify11/Installer/commit/3be2f2eea53dcfcc78ab00c16331dc8246d9330d) and I just have a question for you. Thank you for submitting the fix, by the way.

I am not a programmer, therefore I am just interpreting the code as best as I can. So I could be totally wrong in my interpretation.

For the `PreferExternalManifest` registry setting and the `mmc.exe.manifest` file to be placed during installation, does this require that the user chooses to patch `mmc.exe.mui` as well?

The reason why I ask is because the issue is not caused by any of the system files being patched. It is simply just a bug caused by incompatibility between mmc and the Rectify11 msstyles themes.

Therefore, if the fix (`PreferExternalManifest` registry setting and the `mmc.exe.manifest` file) is to be installed, it should only be dependent on whether or not the user chooses to install the Rectify11 themes during installation.

I just wanted to clarify that since I am not a programmer and I may not be understanding the code changes correctly. Thanks.

**Comment by rounk-ctrl** [comment]
yeah if they patch either mmcbase.dll.mun, mmcndmgr.dll.mun or mmc.exe.mui

**Comment by WildByDesign** [comment]
> wait does it work fine with default ms theme?

Yes, it has no issues with Aero. 

The cause of the issue is how Rectify11 msstyles have per-DPI image resources. That’s a good thing, of course. But the problem is that GDI Scaling has no idea how to handle the per-DPI image resources.

For Aero, there are just single image resources which GDI Scaling then stretches/scales as it requires.

Technically, we could fix this in Rectify11 msstyles. But it might be a step backward for programs other than mmc. Therefore, this workaround is probably the best fix when all things are considered.

**Comment by WildByDesign** [comment]
@WinExperiments beat me to it. He summed it up perfectly, very well said.

**Comment by rounk-ctrl** [comment]
alright

**Comment by WildByDesign** [comment]
@rounk-ctrl  I grabbed a new Actions build up to commit (https://github.com/Rectify11/Installer/commit/6c69fa9913c134781add73e9ea410c621e819d50) and did a clean install of Rectify11 to test the new mmc patch.

- installed all Basic and Themes
- `PreferExternalManifest` was set correctly in the registry from the Rectify11 installer
- `mmc.exe.manifest` never made it to `C:\Windows\System32`

So the only remaining issue is that `mmc.exe.manifest` is not being copied to `C:\Windows\System32` for some reason.

**Comment by WildByDesign** [comment]
I just tested uninstall now:

- `PreferExternalManifest` was correctly undone in the registry from the Rectify11 uninstaller
- `mmc.exe.manifest` was correctly deleted from `C:\Windows\System32`

Uninstall of the mmc-fix works 100%.

**Comment by WildByDesign** [comment]
@rounk-ctrl All good now, dude. Thank you.

MMC DPI working great by default now with Rectify11. I appreciate the time that you put into these code changes to include the fix. Cheers!

**Comment by WildByDesign** [comment]
@rounk-ctrl  Sorry to have to beat a dead horse again on this issue.

But it seems that the `mmc.exe.manifest` file got left out of the `themes.7z` archive for the 3.0 release. So the mmc-fix is currently broken. 

I'm guessing it is because @WinExperiments had made a lot of awesome changes to the msstyles in the lead-up to 3.0 release and maybe on his end didn't realize that the `mmc.exe.manifest` file needed to be packaged into the `themes.7z` archive.

**Comment by rounk-ctrl** [comment]
fixed

**Comment by WildByDesign** [comment]
Thanks, dude. Appreciate it.
