### ISSUE TITLE
Installer stuck at creating restore point

### ISSUE THREAD

**Issue by wealstarr** [Rectify11/Installer#272]
Hi,

Installer gets stuck at "creating restore point"

OS: Windows 11 22H2 build 2283

![image_2023-09-24_202249](https://github.com/Rectify11/Installer/assets/26643729/0a6ef26d-2b52-40c5-bd39-189916106873)

I have windows recovery turned off, I use other recovery solutions.

The issue is with the installer, it mandatory tries to make restore point instead of giving the end user the option to do so.

Please resolve this issue from the installer

Kind regards

**Comment by rounk-ctrl** [comment]
fixed in actions

**Comment by BlankFX1** [comment]
Please add a choice to not create an restore point as this isn't really fixed.
The installer remains in the dialog window "Creating Restore Point..." (or whatever it might be in english...).
