### ISSUE TITLE
New "Bell Icon" replaced by a box in Taskbar 23H2

### ISSUE THREAD

**Issue by Vipin2003** [Rectify11/Installer#274]
### Description

In 23H2, MS introduced a "Bell" icon right to Date&Time. But after patching icons, the bell icon got vanished and a box appears. It should be fixed ASAP in next Action build.

### Steps To Reproduce

Just upgrade ur PC to stable preview version and patch icons only.

### Rectify11 Version

latest from Action...umm...control panel shortcut update

### Windows Version

22621.2361 Stable Moment 4

### Logs

![Screenshot 2023-09-29 210225](https://github.com/Rectify11/Installer/assets/93650504/12e71d64-6a52-4cc7-9d51-19e83776cee2)

**Comment by WildByDesign** [comment]
Same issue. Thank you for reporting.

**Comment by rounk-ctrl** [comment]
yea i fixed it

**Comment by WildByDesign** [comment]
This issue is not fixed. I just uninstalled previous version and installed RC3 fresh and the box is still there on 23H2.

**Comment by rounk-ctrl** [comment]
because you have been affected by it, it wont cause issues to new users

**Comment by Vipin2003** [comment]
Yeah... You have to reinstall windows and use latest action build. Even system restore also won't work. So, the last option remains is clean install

**Comment by WildByDesign** [comment]
Confirmed, fixed. Thank you for your tip on reinstall. I just did a quick 10 minutes Windows in-place repair install and it's all good now.
