### ISSUE TITLE
(text) Even when switching from dark mode to light mode, the text in Windows File Explorer remains white.

### ISSUE THREAD

**Issue by yangyangdaji** [Rectify11/Installer#346]
## Description
Even when switching from dark mode to light mode, the text in Windows File Explorer remains white.

## Windows File Explorer
![mmexport1698845328618](https://github.com/Rectify11/Installer/assets/108261729/ce0173b2-bfb0-4189-b9b1-dabd8759bf72)

White Text

## "Open" or "Save As" dialog [COMDLG32]
![mmexport1698845356525](https://github.com/Rectify11/Installer/assets/108261729/9b3540a9-27e0-440c-89b3-060bef1eddbe)
 
No problem

### Steps To Reproduce

1. Download and install [Rectify11 v3.1](https://github.com/Rectify11/Installer/releases/tag/v-3.1-fixed2) 
2. When choosing visual styles, choose dark mode.
3. Restart PC
4. Switch to Light mode
5.  Open Windows File Explorer

### Rectify11 Version

Rectify11 v3.1

### Windows Version

Windows 11 22621.ni_release.220506-1250

### Logs

NO

**Comment by 0xC4aE1e5** [comment]
Use the control center.

**Comment by yangyangdaji** [comment]
> Use the control center.
Thank you Has been fixed。 

but there are still some other issues. I will open another Issue to discuss them.

**Comment by yangyangdaji** [comment]
> Use the control center.

Thank you Has been fixed。 
but there are still some other issues. I will open another Issue to discuss them.
 
![IMG_20231102_075724](https://github.com/Rectify11/Installer/assets/108261729/c451c308-e136-4544-b5f7-37a00037789e)

**Comment by chadify** [comment]
@yangyangdaji I changed the theme using rectify11 control panel, still the same issue.

**Comment by yangyangdaji** [comment]
> @yangyangdaji I changed the theme using rectify11 control panel, still the same issue

 OK I reopen the Issue

**Comment by yangyangdaji** [comment]
@chadify What version

**Comment by yangyangdaji** [comment]
@chadify Try restart PC

**Comment by chadify** [comment]
> > @yangyangdaji I changed the theme using rectify11 control panel, still the same issue.
> 
> @chadify Rectify11 what version

The latest version. Restarting too didn't help. Sometimes it works sometimes it don't.

**Comment by yangyangdaji** [comment]
> The latest version. Restarting too didn't help. Sometimes it works sometimes it don't.

Um, cc @rounk-ctrl @MishaProductions @WinExperiments

**Comment by rounk-ctrl** [comment]
im not part of the team
