### ISSUE TITLE
Broken File Explorer..

### ISSUE THREAD

**Issue by VitalSkib** [Rectify11/Installer#493]
### Description

Hi. 
Some of the changes between versions (from Actions) [#751](https://github.com/Rectify11/Installer/actions/runs/8227334027) and [#752](https://github.com/Rectify11/Installer/actions/runs/8235478588) break File Explorer for me. 
Version [#751](https://github.com/Rectify11/Installer/actions/runs/8227334027) and below works fine, but after installing version [#752](https://github.com/Rectify11/Installer/actions/runs/8235478588) and newer 
it opens a blank File Explorer window and File Explorer becomes unresponsive.
And I cannot close this window simply by clicking the "Close" button, only through the Task Manager or Restart Explorer.
Disabling Windows Defender (I don't have any third party installed) and rebooting doesn't help.
However, if I switch the theme to the default Windows Dark, then everything works fine again.
I don't have enough knowledge to figure this out on my own, so..
TIA

![File Explorer](https://github.com/Rectify11/Installer/assets/43848892/a3353376-632b-4b96-9f5a-53254f8ac619)

### Steps To Reproduce

Install version [#752](https://github.com/Rectify11/Installer/actions/runs/8235478588) from the Actions and launch File Explorer..

### Rectify11 Version

Rectify11 v3.2.60.0

### Windows Version

Windows 11 Pro 24H2 26080.1

### Logs

Logs, screenshots, etc relevant to this bug.

**Comment by WinExperiments** [comment]
Fixed in commit #763 (version 3.2.63.1)

**Comment by VitalSkib** [comment]
> Fixed in commit #763 (version 3.2.63.1)

Hmm, I installed version **3.2.63.1** ([#763](https://github.com/Rectify11/Installer/actions/runs/8302147950)) and it still doesn't work for me.. 
However, replacing the **`shellstyle.dll`** file from` C:\Windows\Resources\Themes\aero\Shell\NormalColor` 
to `C:\Windows\Resources\Themes\Rectified\Shell\NormalColor` helps.
tia

![2024-03-16](https://github.com/Rectify11/Installer/assets/43848892/0d63d078-0850-48ce-8324-ab1df177561d)
