### ISSUE TITLE
compmgmt.msc Perfomance tab looks broken

### ISSUE THREAD

**Issue by x-0D** [Rectify11/Installer#61]
![image](https://user-images.githubusercontent.com/87000516/207052052-e5c84e2b-63ea-4a85-bcca-4abee281c734.png)

**Comment by XPnerdYT** [comment]
Those are hardcoded, so we cannot fix it easily at the moment.

**Comment by XPnerdYT** [comment]
Okay wait what version is that?

**Comment by XPnerdYT** [comment]
Actually the next rp build should fix it

**Comment by XPnerdYT** [comment]
3.0-RP2 has been released, reinstall it again and check.

**Comment by x-0D** [comment]
> 3.0-RP2 has been released, reinstall it again and check.

![image](https://user-images.githubusercontent.com/87000516/208167182-3545166a-adda-4438-8d95-c78a8d35b636.png)
Still not good, but perfomance icon in left pane changed

**Comment by XPnerdYT** [comment]
Intresting. Let me notify the software department.

**Comment by fytuf** [comment]
> Intresting. Let me notify the software department.

department? we aint a company lo

**Comment by XPnerdYT** [comment]
> department? we aint a company lo

_Just to look professional xD_

**Comment by fytuf** [comment]
lol

**Comment by XPnerdYT** [comment]
For now, just switch between themes, as I don't think this will be adressed anytime soon.
